### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 10,
  "memberId": "hitomis",
  "name": "히토미",
  "age": "18"
}
